### ISSUE TITLE
css必知

### ISSUE THREAD

**Issue by sinner77** [sinner77/daily-practive#21]
* css选择器的特殊性
* 选择器的种类
* 多种布局方式
* 水平垂直居中
* BFC的概念及其作用
* 清除浮动多种方式
* flex布局
* vertical-align用法
* 行内元素与块级元素
* 盒模型
* ....待补充

[有哪些经常被误用的 HTML、JavaScript、CSS 的元素、方法和属性？](https://www.zhihu.com/question/20979831)

**Comment by sinner77** [comment]
css实现子元素水平垂直都居中
```css
// 1.flex子元素可以不固定宽高
.parent{
    display: flex;
    justify-content: center;
    align-items: center;
}
// 2.position+transform子元素可以不固定宽高
.parent{
    position: absolute;
}
.child{
    position: relative;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
// 3.table-cell+inline-block子元素可以不固定宽高
.parent{
	display: table-cell;
	vertical-align: middle;
	text-align: center;
}
.child{
	background: blue;
	display: inline-block;
}
// 4.position+负margin 子元素需固定宽高
.parent{
		width: 500px;
		height: 500px;
		border: 1px solid red;
		position: relative;
	}
.child{
	position: absolute;
	top: 50%;
	left: 50%;
	width: 100px;
	height: 100px;
	background: red;
	margin-left: -50px;
	margin-top: -50px;
}
```
